# Generated by Django 2.2.16 on 2022-07-02 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created',)},
        ),
    ]
